spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 94642466533-p3tvrk3883ad3d8kftd9mrboipi89poo.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://www.tigerbk.com/api/oauth2/mobile/google
            authorization-grant-type: authorization_code
            scope: profile, email, name
          kakao:
            authorization-grant-type: authorization_code
            client-id: 4efec10a9ec33d60ed0137af92b0abdc  
            client-secret: PN5Wwt5DVy2xBIuehQK5jnKNsRzWASme
            redirect-uri: https://www.tigerbk.com/api/oauth2/mobile/kakao
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao
          naver:
            client-id: AkO9to2gAVqyjGMInLAQ
            client-secret: z7ZchdO2Uq
            redirect-uri: https://www.tigerbk.com/api/oauth2/mobile/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response 